### ISSUE TITLE
Paragraphs Set at 70% Width

### ISSUE THREAD

**Issue by kmgdevelopment** [sjelfull/craft-entry-instructions#11]
The CSS has paragraphs set at a max-width of 70%. Any particular reason for this? It's causing my text to wrap unnecessarily.

**Comment by sjelfull** [comment]
@adrienne do you know if this has to do with your latest changes?

**Comment by adrienne** [comment]
@sjelfull - the default CSS it uses is literally exactly what you had in there before, i didn't make any modifications. And i remember seeing that paragraphs were set to 70% width before my changes, honestly, and thinking that was odd. 

If you want to modify the default CSS for folks, it's in this file now: https://github.com/sjelfull/craft-entry-instructions/blob/master/src/models/Settings.php

**Comment by heymarkreeves** [comment]
@kgrote FWIW, I've fixed this in the Custom CSS overrides using `p {max-width: 100%;}`.
