### ISSUE TITLE
Default Craft instruction styles are used when field is used in NEO block

### ISSUE THREAD

**Issue by jsunsawyer** [sjelfull/craft-entry-instructions#12]
Custom styles don't even seem to load. Using `!important` does not override any styles.

**Comment by jsunsawyer** [comment]
This also seems to affect its use in Matrix fields.

![screen shot 2018-12-07 at 10 52 57 am](https://user-images.githubusercontent.com/1007191/49666933-55c10780-fa0e-11e8-96e5-e492a1166456.png)

**Comment by vaughn-taylor** [comment]
It seems that there has been no resolution to this? I'm using NEO and Matrix fields and I'd like to be able to apply custom styling to my instruction fields.

**Comment by sjelfull** [comment]
This should be fixed in 1.0.5
