### ISSUE TITLE
Cannot override .instructions:before

### ISSUE THREAD

**Issue by heymarkreeves** [sjelfull/craft-entry-instructions#14]
**Describe the bug**
I'm trying to override `.instructions:before` with `:before { }` in the **Custom CSS** field. When that's processed, it's prepended with `.instructions ` resulting in `.instructions :before`, which is not an override. (Note the space.)

It seems an element was added with a blue background color, which is clashing with the custom styles I've applied to `.instructions`, entered as `{ }` with no preceding class name.

Can the `:before` styles be removed? I've used this plugin in the past without running into this problem.

**To Reproduce**
Style the instructions using `{ }`. Attempt to style `:before { }`.

**Expected behavior**
I want to remove the blue border appearing to the left by using CSS overrides, as supported.

**Screenshots**
![Screen Shot 2019-10-15 at 3 56 45 PM](https://user-images.githubusercontent.com/49657/66865072-7a5a0a00-ef64-11e9-9643-77c9cf10c40d.png)
![Screen Shot 2019-10-15 at 3 56 59 PM](https://user-images.githubusercontent.com/49657/66865073-7a5a0a00-ef64-11e9-9675-c1b46333c01e.png)

**Comment by sjelfull** [comment]
Thanks, tagged a release just now with your PR.
