### ISSUE TITLE
Unable to find component class 'EntryInstructions_Instructions'

### ISSUE THREAD

**Issue by watershed** [sjelfull/craft-entry-instructions#18]
### Describe the bug

Entry Instructions fields are displaying an error message: 

> “Unable to find component class 'EntryInstructions_Instructions'.”

The defined field content is displaying above the error message (but not styling?) -- screenshot 1

### To Reproduce

1. Entry Instructions was working fine under a Craft 2 install
2. When that Craft install was updated to Craft **3.4.15**, and all plugins subsequently updated, the issue arose.

NB: 

* The plugin is listed as 'Installed' under `Settings > System (group) > Plugins` -- screenshot 2
* It is not shown under `Settings > Plugins (group)` -- not sure if it should be -- screenshot 3

#### Screenshot 1
<img width="584" alt="1_craftcms_edit-entry_entry-instructions-field-error-message" src="https://user-images.githubusercontent.com/219060/79692686-72a25780-825e-11ea-8d76-fbaeb7d339a0.png">

#### Screenshot 2
<img width="993" alt="2_craftcms_settings_system-group_plugins-sintalled-status" src="https://user-images.githubusercontent.com/219060/79692688-746c1b00-825e-11ea-9118-c96278405672.png">

#### Screenshot 3
<img width="778" alt="3_craftcms_settings_plugins-group" src="https://user-images.githubusercontent.com/219060/79692692-759d4800-825e-11ea-8bd6-4122ea9b8d29.png">

**Comment by sjelfull** [comment]
Hey, this plugin is a port of the Craft 2 version, that was developed by someone else. It does not include any migrations to "upgrade" the Craft 2 version, as it technically is two different plugins.

I think the simplest way for you to fix this is to go into the field settings and selecting the `Field Instructions` field type.

![image](https://user-images.githubusercontent.com/10508/79727585-e2f7ba00-82ec-11ea-995f-80979e67e6ee.png)

It should not show on Settings > Plugins (group).

**Comment by watershed** [comment]
Perfect, thanks. That worked :)
