### ISSUE TITLE
Instruction settings do not render

### ISSUE THREAD

**Issue by furioursus** [sjelfull/craft-entry-instructions#19]
**Describe the bug**
Can’t add instructions to field, doesn’t render at all

**To Reproduce**
1. Create a new field
2. Choose "Entry Instructions" field type
3. Scroll down to bottom of page
4. Instruction setup is missing, only Custom CSS window is present

**Expected behavior**
I should be seeing the instructions field and be able to set up the field from here.

**Screenshots**
![CleanShot 2020-07-01 at 14 32 53](https://user-images.githubusercontent.com/366427/86293591-c8bd4080-bba7-11ea-839c-ad1f20a40293.png)

**Additional context**
- Craft version: 3.4.25
- `craftcms/feed-me` 4.2.3
- `craftcms/redactor` 2.6.1
- `doublesecretagency/craft-inventory` 2.1.0
- `fruitstudios/linkit` 1.1.11
- `mmikkel/cp-field-inspect` 1.1.3
- `nystudio107/craft-imageoptimize` 1.6.14
- `nystudio107/craft-minify` 1.2.10
- `nystudio107/craft-seomatic` 3.3.8
- `nystudio107/craft-twigpack` 1.2.3
- `percipioglobal/craft-colour-swatches` 1.2.8
- `putyourlightson/craft-blitz` 3.6.5
- `putyourlightson/craft-sprig` 1.0.0-beta.4
- `superbig/craft-entry-instructions` 1.0.7
- `vaersaagod/dospaces` 1.1.2
- `vaersaagod/matrixmate` 1.2.5
- `verbb/navigation` 1.3.21
- `verbb/super-table` 2.5.1

**Comment by sjelfull** [comment]
This plugin has been abandoned in favour of UI elements in Craft.
