### ISSUE TITLE
Make # links open tabs

### ISSUE THREAD

**Issue by outline4** [sjelfull/craft-entry-instructions#4]
I came across https://github.com/mildlygeeky/craft-instruction-links wich will open tabs from instructions. it would be nice if this was in your plugin as well 🥇

**Comment by sjelfull** [comment]
https://github.com/mildlygeeky/craft-instruction-links doesn't do anything regarding tab links (if we are talking about tabs on the Edit screen), and as far as I know, it's not possible to link to tabs from field instructions.

How can I replicate this?

**Comment by outline4** [comment]
Oh I am sorry... You are right the craft instructions links plugin does not open a tab from the edit screen.  
In fact it would be nice if a link could open a tab in edit view like this:   
[please fill out the details](#tab-details). 
and then open the tab "details"... 
I know it has to be done with js... the link itself is not sufficient enough.
