### ISSUE TITLE
Suggestion: Add "Notes" to title

### ISSUE THREAD

**Issue by darylknight** [sjelfull/craft-entry-instructions#5]
Tiny suggestion - I've been looking for a plugin like this for a while to replace Sprout Notes, and this wasn't showing up in searches in the Plugin Store. If anyone else is doing the same as me, it might improve visibility to add "Notes" as a searchable term. I'm not sure what fields the Plugin Store searches, but somewhere may help more people see this.

**Comment by sjelfull** [comment]
Added it as a keyword, and it now shows up.
