### ISSUE TITLE
HTML Tags Not Parsed

### ISSUE THREAD

**Issue by kmgdevelopment** [sjelfull/craft-entry-instructions#9]
I'm probably just being dense but when I use HTML tags in my instructions field they're not parsed so I get a text `<p>` tag. Presumably it should be possible to use HTML tags since the CSS needs to target something so I'm not sure what I'm doing wrong here.

**Comment by sjelfull** [comment]
It does support markdown, which will be converted to HTML, which in turn can be targeted by CSS.

Not sure if HTML should also work out of the box?

**Comment by kmgdevelopment** [comment]
Ah ha! Yeah I missed where it was parsed in markdown. OK I'm good now, thanks!
